---
argument_specs:
  main:
    short_description: HPE iLO HTTPS Certificate
    description:
      - This role generates a new HTTPS Certificate for an HPE iLO, if an existing certificate doesn't exist or needs renewal.
      - This role will use another role to generate the private key, CSR, and certificate.
      - The role can be supplied by setting the `ilo_certificate_type` to an existing type or setting it to `custom` and supplying a role name through the `ilo_certificate_role` variable.
      - The role referenced must output an unencrypted private key in the `cert_private_key_content` variable and the certificate in the `cert_certificate_content` variable.
    author: Jim Tarpley (@trippsc2)
    options:
      ilo_base_url:
        type: str
        required: true
        description:
          - The base URL of the HPE iLO.
      ilo_username:
        type: str
        required: true
        description:
          - The username to use when connecting to the HPE iLO.
      ilo_password:
        type: str
        no_log: true
        required: true
        description:
          - The password to use when connecting to the HPE iLO.
      ilo_certificate_regenerate_days:
        type: int
        required: false
        default: 30
        description:
          - The number of days before the certificate expiration to regenerate the CSR.
      ilo_certificate_type:
        type: str
        required: true
        choices:
          - self_signed
          - adcs_signed
          - vault_signed
          - acme_dns_signed
          - custom
        description:
          - The type of certificate to generate.
          - If set to `self_signed`, the role will use the **trippsc2.general.self_signed_certificate** role.
          - If set to `adcs_signed`, the role will use the **trippsc2.adcs.signed_certificate** role.
          - If set to `vault_signed`, the role will use the **trippsc2.hashi_vault.signed_certificate** role.
          - If set to `acme_dns_signed`, the role will use the **trippsc2.general.acme_dns_certificate** role.
          - If set to `custom`, the role will use the role supplied in the `ilo_certificate_role` variable.
      ilo_certificate_role:
        type: str
        required: false
        description:
          - The role to use to generate the private key, CSR, and certificate.
          - This is required if *ilo_certificate_type* is set to `custom`. Otherwise, it is not used.
