---
namespace: trippsc2
name: hpe
version: 1.0.0
readme: README.md
authors:
  - Jim Tarpley (@trippsc2)
description: This collection contains plugins and/or roles for configuring HPE servers.

license_file: 'LICENSE'

tags:
  - infrastructure
  - security
  - tools

dependencies: {}

repository: https://github.com/trippsoft/ansible-collection-hpe.git

manifest:
  directives:
    - recursive-include roles/* *.md
    - recursive-include roles/*/files **
    - exclude galaxy.yml galaxy.yaml MANIFEST.json FILES.json *.tar.gz
    - recursive-exclude tests/output **
    - recursive-exclude roles/*/molecule **
    - recursive-exclude molecule **
    - global-exclude /.* /__pycache__
