---
name: Generate Role Docs
'on':
  workflow_dispatch: {}
  push:
    branches:
      - main
    paths:
      - galaxy.yml
      - roles/ilo_https_certificate/.aar_doc.yml
      - roles/ilo_https_certificate/README.md
      - roles/ilo_https_certificate/meta/argument_specs.yml
      - roles/ilo_https_certificate/meta/main.yml
defaults:
  run:
    working-directory: 'trippsc2.hpe'
jobs:
  docs_ilo_https_certificate:
    name: Generate ilo_https_certificate role documentation
    permissions:
      contents: write
    runs-on:
      - self-hosted
      - linux
      - ansible
      - x64
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          path: trippsc2.hpe
          ref: main
      - name: Generate ilo_https_certificate role documentation
        working-directory: 'trippsc2.hpe'
        run: |
          source ~/venv/ansible-2.16/bin/activate
          cd ./roles/ilo_https_certificate
          aar-doc . markdown
          git config user.name "GitHub Actions"
          git config user.email "github-actions@github.com"
          git add README.md || /bin/true
          git commit -m "Update ilo_https_certificate role documentation." || /bin/true
          git push origin main
          deactivate
